# Generated by Django 5.2.7 on 2025-10-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopkeeper',
            options={},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='shopkeeper',
            table='Shopkeeper',
        ),
    ]
