# Generated by Django 5.2.7 on 2025-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default=1, upload_to='product/images/'),
            preserve_default=False,
        ),
    ]
