# Generated by Django 5.2.7 on 2025-11-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_shopkeeper_options_and_more'),
        ('products', '0003_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.brandname'),
        ),
        migrations.AlterField(
            model_name='vendorproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='vendorproducts',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_products', to='accounts.shopkeeper'),
        ),
    ]
