# Generated by Django 5.2.7 on 2025-11-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_parent_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='Product',
            new_name='product',
        ),
    ]
